### ISSUE TITLE
Add a play button to go along with slider

### ISSUE THREAD

**Issue by andrewhill157** [CSE512-15S/a3-tdurham-ajh24-chiasson#2]
This is just an idea, but I think it would be cool to implement a play button to go along with the slider. This would require a button, a callback to set up calling a function at set intervals, and then the ability to turn this off temporarily if the user moves the slider manually.

There would also need to be some formatting to have the slider and play button alongside each other.

**Comment by tdurham86** [comment]
I added a play/pause button. It's not very fancy, but does the trick. I also tried implementing an alternative version of the slider by simply wiring up a standard HTML range-type input. It works pretty well, but is probably less customizable than the D3 slider. We can play around with them when we meet.

**Comment by andrewhill157** [comment]
I was looking for a better alternative to the custom SVG shapes anyway, so this is great. I added CSS styling for both that and the play button in c9ada0693aa0dc7fa05010373524ffa8a8e6a645. It's pretty easy to make it look less 90's haha.

There may or may not be browser compatibility problems -- those should be easy enough to sort out.
